config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :variables
  resources :students do
    collection { post :import }
  end
  post 'payments/export'
  resources :sections
  resources :home
  root 'home#defaulters'
  get 'defaulters',to: 'home#defaulters',as: :defaulters
  put 'destroy_all',to: 'students#destroy_all',as: :destroy_all
  devise_for :users

end

app/models/student.rb
class Student < ActiveRecord::Base
    # require 'roo'
    belongs_to :section
    has_many :payments, :dependent => :destroy
    
    
    # def self.to_csv(options = {})
    #   CSV.generate(options) do |csv|
    #       csv << column_names
    #       all.each do |student|
    #           csv << student.attributes.values_at(*column_names)
    #       end
    #   end
    # end
    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        if spreadsheet
            header = spreadsheet.row(1)
            (2..spreadsheet.last_row).each do |i|
                header = spreadsheet.row(i)
                student = new
                student.admission_number = header[0]
                student.name = header[1]
                student.tuition_fee = header[2]
                section = Section.find_by(name: header[3])
                if section.present?
                    student.section_id = section.id
                else
                   Section.create(name: header[3])
                   student.section_id = Section.find_by(name: header[3]).id
                end
                student.save!
                # end
            end
        end
    end    
    def self.open_spreadsheet(file)
        if file
            case File.extname(file.original_filename)
            when ".csv" then Csv.new(file.path, nil, :ignore)
            when ".xls" then Excel.new(file.path, nil, :ignore)
            when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
            else raise "Unknown file type: #{file.original_filename}"
            end
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def destroy_all
    Student.find_each(&:destroy)
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Students was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def import
    Student.import(params[:file])
    redirect_to students_path, notice: "Students imported"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :section_id, :admission_number,:tuition_fee)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= bootstrap_form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select :section_id,options_for_select(Section.all.collect { | section | [section.name, section.id] }),label: "Class" %>
  </div>
  <div class="field">
    <%= f.text_field :admission_number %>
  </div>
  <div class="field">
    <%= f.number_field :tuition_fee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.1.erb
<!--<div class="container">-->
<h1>All Students</h1>

<%= link_to 'New Student', new_student_path,class: "btn btn-success pull-right" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Admission number</th>
      <th>Name</th>
      <th>Tuition Fee</th>
      <th>Class</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.admission_number %></td>
        <td><%= student.name %></td>
        <td><%= student.tuition_fee %></td>
        <td><%= student.section.name %></td>
        <td><%= link_to 'Add Payment', new_payment_path(for: student) %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--</div>-->

app/views/students/index.html.erb
<div class = "animated fadeIn" ng-app="Studentsr" ng-controller="StudentCtrl">
  <div id="dashboard-con">
    <div>
      <ng-view></ng-view>
      <div class="dashboard-left-cell">
        <div class="admin-content-con">
          <header class="clearfix">
            <h3 class="pull-left">All Students</h3>
            <div class = "divider pull-right">
              <%= link_to "Add new student", new_student_path, :class => "btn btn-sm btn-primary pull-right", :role => "button" %> 
            </div>
            <div class = "divider pull-right">
              <%= link_to 'Delete all', destroy_all_path, method: :put, :class => 'btn btn-sm btn-danger', :role => "button", :data => {confirm: 'Are you sure you want to delete all students?'} %> 
            </div>
            
            <div class="col-sm-2 pull-right lil">
            <input type="text" class="form-control-special" ng-model="searchString" placeholder="Search Students"/>
            </div>
           
          </header>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Admission number</th>
                <th>Name</th>
                <th>Tuition Fee</th>
                <th>Class</th>
                <th colspan="4">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr ng-repeat="student in students | searchFor:searchString">
                  <td>{{student.admission_number}}</td>
                  <td>{{student.name}}</td>
                  <td>{{student.tuition_fee}}</td>
                  <td>{{student.section}}</td>
                  <td>
                    <%= link_to 'Add Payment', URI::unescape(new_payment_path(for: '{{student.id}}')), :class => 'btn btn-xs btn-success' %>
                    <%= link_to 'Edit', URI::unescape(edit_student_path(:id => '{{student.id}}')), :class => 'btn btn-xs btn-warning', :role => "button" %>
                    <!--<= link_to 'View', URI::unescape(student_path(:id => '{{student.id}}')), :class => 'btn btn-xs btn-primary', :role => "button" %>-->
                    <%= link_to 'Delete', URI::unescape('students/{{student.id}}'), method: :delete, :class => 'btn btn-xs btn-danger', :role => "button", :data => {confirm: 'Are you sure you want to delete this?'} %>
                  </td>
              </tr>
            </tbody>
          </table>
          
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var stdMod = angular.module('Studentsr', []); 
  stdMod.controller('StudentCtrl', function ($rootScope, $http) {
    $rootScope.students = []
    <% if @students!=nil%>
      <% @students.each do |student| %>
        $rootScope.students.push({
          id: '<%= student.id %>',
          name:'<%= student.name.titleize() %>',
          admission_number: '<%= student.admission_number %>',
          tuition_fee: '<%= student.tuition_fee %>',
          section: '<%= student.section.name %>'
          
        })
    <% end %>
  <% end %>
  });
  stdMod.filter('searchFor', function(){
  return function(arr, searchString){
    if(!searchString){
      return arr;
    }
    var result = [];
    searchString = searchString.toLowerCase();
    angular.forEach(arr, function(item){
      if(item.id.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.name.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.admission_number.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.tuition_fee.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }else if(item.section.toLowerCase().indexOf(searchString) !== -1){
        result.push(item);
      }
    });
    return result;
  };
  });
</script>

app/views/students/new.html.erb
<h2>Import from excel</h2>
<p>Format of excel file: Admission Number | Name | Tuition Fee | Class </p>
<%= form_tag import_students_path, multipart: true do %>
    <%= file_field_tag :file, required: true %>
    <br>
    <%= submit_tag "Import" %>
<% end %>
<h2>OR Add new Student Manually</h2>
<%= render 'form' %>

<%= link_to 'Back to all Students', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @student.section_id %>
</p>

<p>
  <strong>Admission number:</strong>
  <%= @student.admission_number %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>