config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :variables
  resources :students do
    collection { post :import }
  end
  post 'payments/export'
  resources :sections
  resources :home
  root 'home#defaulters'
  get 'defaulters',to: 'home#defaulters',as: :defaulters
  put 'destroy_all',to: 'students#destroy_all',as: :destroy_all
  devise_for :users

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :student
  belongs_to :section
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /payments
  # GET /payments.json
  def index
    @search = Payment.search(params[:q])
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @variable = Variable.last
    if !@variable.present?
      redirect_to new_variable_path, notice: "Set These valuese first. Then You'll be able to add Payments."
    end
    if params[:for].present?
      @student = Student.find(params[:for])
    end
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.student_id = Student.find_by_admission_number(@payment.student_id).id
    @payment.section_id = Student.find(@payment.student_id).section_id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to students_path, notice: 'Payment Record was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def export
    package = Axlsx::Package.new
    workbook = package.workbook
    workbook.add_worksheet(name: "January") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "January").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "February") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "February").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "March") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "March").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "April") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "April").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "May") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "May").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "June") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "June").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "July") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "July").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "August") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "August").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "September") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "September").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "October") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "October").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "November") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "November").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    # 
    workbook.add_worksheet(name: "December") do |sheet|
      sheet.add_row ["Admission Number", "Name","Class"]
      students = Student.where.not(id: Payment.where(month: "December").map(&:student_id))
      students.each do |st|
        sheet.add_row [st.admission_number, st.name,st.section.name]
      end
    end
    
    send_data package.to_stream.read, :filename => "defaulters.xlsx"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:student_id, :section_id, :year, :month, :date, :payment_mode, :tuition_fee,:library_fund,:computer_fee,:science_lab_fee,:video_music_fee,:sports_fund,:workbook_charges,:AC_charges,:generator_charges, :fine, :previous_books, :annual_fund, :total)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div ng-app>

<%= bootstrap_form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.text_field :student_id,required: true,label: "Admission Number of Student *",value: (@student.admission_number if @student.present?) %>
      </div>
      <div class="field">
        <%= f.hidden_field :year,value: @variable.year %>
      </div>
      <div class="field">
        <%= f.hidden_field :month,value: @variable.month %>
      </div>
      <div class="field">
        <%= f.hidden_field :date,value: @variable.date %>
      </div>
      <div class="field">
        <%= f.hidden_field :payment_mode,value: @variable.payment_mode %>
      </div>
      <div class="field">
        <%= f.number_field :tuition_fee,"ng-init": "fee= #{(@student.tuition_fee if @student.present?) || 0}", "ng-model": "fee" %>
      </div>
      <div class="field">
        <%= f.number_field :library_fund,"ng-init": "library_fund= 0", "ng-model": "library_fund" %>
      </div>
      <div class="field">
        <%= f.number_field :computer_fee,"ng-init": "computer_fee= 0", "ng-model": "computer_fee" %>
      </div>
      <div class="field">
        <%= f.number_field :science_lab_fee,"ng-init": "science_lab_fee= 0", "ng-model": "science_lab_fee",label: "Video/Music Fee" %>
      </div>
      <div class="field">
        <%= f.number_field :video_music_fee,"ng-init": "video_music_fee= 0", "ng-model": "video_music_fee" %>
      </div>
      <div class="field">
        <%= f.number_field :sports_fund,"ng-init": "sports_fund= 0", "ng-model": "sports_fund" %>
      </div>
    </div>
    <div class="col-md-6">
      
      <div class="field">
        <%= f.number_field :workbook_charges,"ng-init": "workbook_charges= 0", "ng-model": "workbook_charges" %>
      </div>
      <div class="field">
        <%= f.number_field :AC_charges,"ng-init": "AC_charges= 0", "ng-model": "AC_charges",label: "AC charges" %>
      </div>
      <div class="field">
        <%= f.number_field :generator_charges,"ng-init": "generator_charges= 0", "ng-model": "generator_charges" %>
      </div>
      <div class="field">
        <%= f.number_field :fine,"ng-init": "fine= 0", "ng-model": "fine"  %>
      </div>
      <div class="field">
        <%= f.number_field :previous_books,"ng-init": "previous= 0", "ng-model": "previous" %>
      </div>
      <div class="field">
        <%= f.number_field :annual_fund,"ng-init": "annual_fund= 0", "ng-model": "annual_fund" %>
      </div>
      <div class="field">
        <%= f.hidden_field :total, :value => '{{fine--fee--previous--annual_fund--library_fund--computer_fee--science_lab_fee--video_music_fee--sports_fund--workbook_charges--AC_charges--generator_charges}}' %>
      </div>
      <h2> Total: {{fine--fee--previous--annual_fund--library_fund--computer_fee--science_lab_fee--video_music_fee--sports_fund--workbook_charges--AC_charges--generator_charges}} </h2>
      <div class="actions">
        <%= f.submit  class: "btn btn-success" %>
      </div>
    </div>
  </div>
  
  
<% end %>

</div>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>All Payment Records</h1>
<%= link_to 'New Payment', new_payment_path,class: "btn btn-success pull-right" %>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Class</th>
      <th>Year</th>
      <th>Month</th>
      <th>Date</th>
      <th>Payment mode</th>
      <th>Tuition fee</th>
      <th>Fine</th>
      <th>Previous books</th>
      <th>Annual fund</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.student.name %></td>
        <td><%= payment.section.name %></td>
        <td><%= payment.year %></td>
        <td><%= payment.month %></td>
        <td><%= payment.date %></td>
        <td><%= payment.payment_mode %></td>
        <td><%= payment.tuition_fee %></td>
        <td><%= payment.fine %></td>
        <td><%= payment.previous_books %></td>
        <td><%= payment.annual_fund %></td>
        <td><%= payment.total %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payments/new.html.erb
<div class="row">
    <div class="col-md-8">
        <h1>New Payment</h1>
        
        <%= render 'form' %>
    </div>
    
    <div class="col-md-4">
        <h1>Check these values</h1>
        <p><b>Date:</b>    <%= @variable.date %></p>
        <p><b>Month:</b>   <%= @variable.month %></p>
        <p><b>Year:</b>    <%= @variable.year %></p>
        <p><b>Payment Mode:</b><%= @variable.payment_mode %></p>
        <strong><%= link_to 'Change these values', edit_variable_path(Variable.last.id),class: "btn btn-success" %></strong>
    </div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @payment.student.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @payment.section.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @payment.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @payment.month %>
</p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @payment.payment_mode %>
</p>

<p>
  <strong>Tuition fee:</strong>
  <%= @payment.tuition_fee %>
</p>

<p>
  <strong>Fine:</strong>
  <%= @payment.fine %>
</p>

<p>
  <strong>Library Fund:</strong>
  <%= @payment.library_fund %>
</p><p>
  <strong>Computer Fee:</strong>
  <%= @payment.computer_fee %>
</p><p>
  <strong>Science Lab Fee:</strong>
  <%= @payment.science_lab_fee %>
</p><p>
  <strong>Video/Music Fee:</strong>
  <%= @payment.video_music_fee %>
</p><p>
  <strong>Sports Fund:</strong>
  <%= @payment.sports_fund %>
</p><p>
  <strong>Workbook Charges:</strong>
  <%= @payment.workbook_charges %>
</p><p>
  <strong>AC Charges:</strong>
  <%= @payment.AC_charges %>
</p>
<p>
  <strong>Previous books:</strong>
  <%= @payment.previous_books %>
</p>

<p>
  <strong>Annual fund:</strong>
  <%= @payment.annual_fund %>
</p>

<p>
  <strong>Total:</strong>
  <%= @payment.total %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>