config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :variables
  resources :students do
    collection { post :import }
  end
  post 'payments/export'
  resources :sections
  resources :home
  root 'home#defaulters'
  get 'defaulters',to: 'home#defaulters',as: :defaulters
  put 'destroy_all',to: 'students#destroy_all',as: :destroy_all
  devise_for :users

end

app/models/variable.rb
class Variable < ActiveRecord::Base
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
  end

  # GET /variables/new
  def new
    @variable = Variable.new
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render :show, status: :created, location: @variable }
      else
        format.html { render :new }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { render :show, status: :ok, location: @variable }
      else
        format.html { render :edit }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url, notice: 'Variable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variable
      @variable = Variable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variable_params
      params.require(:variable).permit(:year, :month, :date, :payment_mode)
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= bootstrap_form_for(@variable) do |f| %>
  <% if @variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% @variable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :year,options_for_select((2017..2025)) %>
  </div>
  <div class="field">
    <%= f.select :month,[["January"],["February"],["March"],["April"],["May"],["June"],["July"],
    ["August"],["September"],["October"],["November"],["December"]] %>
  </div>
  <div class="field">
    <%= f.select :date,options_for_select((1..31)) %>
  </div>
  <div class="field">
    <%= f.select :payment_mode,[["Bank"],["Cash"]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variables/edit.html.erb
<div class="row">
    <div class="col-md-4">
        <h3>Current values:</h3>
        <table class="table">
            <tr>
                <td><strong>Year:</strong></td>
                <td><%= @variable.year %></td>
            </tr>
            <tr>
                <td><strong>Month:</strong></td>
                <td><%= @variable.month %></td>
            </tr>
            <tr>
                <td><strong>Date:</strong></td>
                <td><%= @variable.date %></td>
            </tr>
            <tr>
                <td><strong>Payment Mode:</strong></td>
                <td><%= @variable.payment_mode %></td>
            </tr>
        </table>
    
    </div>
    <div class="col-md-8">
        <h3>Update These Values</h3>
        
        <%= render 'form' %>
    </div>    
</div>

app/views/variables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Variables</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Month</th>
      <th>Date</th>
      <th>Payment mode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variables.each do |variable| %>
      <tr>
        <td><%= variable.year %></td>
        <td><%= variable.month %></td>
        <td><%= variable.date %></td>
        <td><%= variable.payment_mode %></td>
        <td><%= link_to 'Show', variable %></td>
        <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
        <td><%= link_to 'Destroy', variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>Set these Variables</h1>

<%= render 'form' %>

app/views/variables/show.html.erb
<h3>Current values:</h3>
<table class="table">
    <tr>
        <td><strong>Year:</strong></td>
        <td><%= @variable.year %></td>
    </tr>
    <tr>
        <td><strong>Month:</strong></td>
        <td><%= @variable.month %></td>
    </tr>
    <tr>
        <td><strong>Date:</strong></td>
        <td><%= @variable.date %></td>
    </tr>
    <tr>
        <td><strong>Payment Mode:</strong></td>
        <td><%= @variable.payment_mode %></td>
    </tr>
</table>

<%= link_to 'Update these values', edit_variable_path(@variable) %> |